apiVersion: apps/v1
kind: Deployment
metadata:
  name: informer
  namespace: decmgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: informer
  template:
    metadata:
      labels:
        app: informer
    spec:
      serviceAccountName: decmgmt-sa
      containers:
        - name: informer

          image: informer:1680823975
          env:
            - name: ENDPOINT_API
              value: "http://processing.decmgmt:9000"
          ports:
            - containerPort: 8080
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: decmgmt-watch-services
  namespace: decmgmt
rules:
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: decmgmt-sa
  namespace: decmgmt
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: decmgmt-watch-services-binding
  namespace: decmgmt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: decmgmt-watch-services
subjects:
  - kind: ServiceAccount
    name: decmgmt-sa
    namespace: decmgmt

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing-deployment
  namespace: decmgmt

spec:
  replicas: 2
  selector:
    matchLabels:
      app: processing
  template:
    metadata:
      labels:
        app: processing
    spec:
      serviceAccountName: decmgmt-sa
      containers:
        - name: processing
          image: processing:1680823975
          ports:
            - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: processing
  namespace: decmgmt

spec:
  ports:
    - name: "9000"
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: processing
  type: ClusterIP

