apiVersion: v1
kind: Namespace
metadata:
  name: homepage
---
apiVersion: apps/v1
kind: Deployment
metadata:

  labels:
    app: homepage
  name: homepage
  namespace: homepage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: homepage

  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - image: homepage-service:1680477990
          imagePullPolicy: Never #very important for rancher
          name: homepage-service
          env:
            - name: ENDPOINT_USER_SERVICE
              value: "http://user.user:8080"
            - name: ENDPOINT_RBAC_ENDPOINT
              value: "http://rbac.rbac:8080"
          ports:
            - containerPort: 8100
              name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: homepage
  name: homepage
  namespace: homepage
spec:
  ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8100
  selector:
    app: homepage
  type: ClusterIP
