apiVersion: v1
kind: Namespace
metadata:
  name: rbac
---
apiVersion: apps/v1
kind: Deployment
metadata:

  labels:
    app: rbac
  name: rbac
  namespace: rbac
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rbac

  template:
    metadata:
      labels:
        app: rbac
    spec:
      containers:
      - image: rbac-service:1680477990
        imagePullPolicy: Never
        name: rbac-service
        ports:
          - containerPort: 8090
            name: http
---
apiVersion: v1
kind: Service
metadata:

  labels:
    app: rbac
    decMgmtProvides: rbacService
  name: rbac
  namespace: rbac
spec:
  ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8090
  selector:
    app: rbac
  type: ClusterIP
