apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: my-webhook
webhooks:
  - name: my-webhook.example.com
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    clientConfig:
      url: https://a43d-2001-a61-3b2f-c801-e4df-feab-3dd3-a53b.eu.ngrok.io/validate

    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        resources:
          - pods
          - services
          - deployments
        operations:
          - CREATE
          - UPDATE
          - DELETE
